### ISSUE TITLE
Waybar issue

### ISSUE THREAD

**Issue by longwasu** [MathisP75/summer-day-and-night#1]
Missing file ~/.config/waybar/scripts/dunst.sh therefore I can't run waybar.

**Comment by MathisP75** [comment]
Oh sorry, I will add the script folder as soon as I get the time

**Comment by MathisP75** [comment]
I added it

**Comment by FrancescoAlizzi** [comment]
Now there are not  errors on themes directories, but other are present on  ~/.config/hypr/hyprland.conf  . Also I can't see the waybar, and if i type "exec waybar" I see this (see the picture). Sorry to bother

![Image](https://github.com/user-attachments/assets/6d0dfded-1e49-4827-b671-9c7bedbce6e9)
